/**
 * Cost of Living (COL) Data for Retirement Calculator
 *
 * All indices are normalized to New York City = 100
 * Higher numbers indicate higher costs
 *
 * Data sources: Numbeo, Expatistan, and other COL databases
 * Data year: 2024-2025
 */

export interface CityData {
  city_id: string;
  city_name: string;
  country: string;
  region: string;              // Geographic region for filtering
  base_index: number;          // Overall cost of living index
  housing_index: number;       // Rent/housing costs
  food_index: number;          // Groceries and dining
  transport_index: number;     // Transportation costs
  healthcare_index: number;    // Healthcare and insurance
  utilities_index: number;     // Utilities (electricity, water, internet)
  tax_index: number;           // Income tax burden (effective rate comparison)
  data_year: number;
  confidence: 'low' | 'medium' | 'high';
}

export const CITIES: CityData[] = [
  // ============================================================================
  // UNITED STATES - Major Cities
  // ============================================================================
  {
    city_id: 'nyc',
    city_name: 'New York City',
    country: 'United States',
    region: 'North America',
    base_index: 100,
    housing_index: 100,
    food_index: 100,
    transport_index: 100,
    healthcare_index: 100,
    utilities_index: 100,
    tax_index: 100,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'sf',
    city_name: 'San Francisco',
    country: 'United States',
    region: 'North America',
    base_index: 102,
    housing_index: 115,
    food_index: 98,
    transport_index: 95,
    healthcare_index: 105,
    utilities_index: 85,
    tax_index: 105,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'la',
    city_name: 'Los Angeles',
    country: 'United States',
    region: 'North America',
    base_index: 85,
    housing_index: 95,
    food_index: 90,
    transport_index: 88,
    healthcare_index: 100,
    utilities_index: 82,
    tax_index: 102,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'seattle',
    city_name: 'Seattle',
    country: 'United States',
    region: 'North America',
    base_index: 88,
    housing_index: 92,
    food_index: 92,
    transport_index: 85,
    healthcare_index: 98,
    utilities_index: 75,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'boston',
    city_name: 'Boston',
    country: 'United States',
    region: 'North America',
    base_index: 90,
    housing_index: 95,
    food_index: 92,
    transport_index: 90,
    healthcare_index: 105,
    utilities_index: 95,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'dc',
    city_name: 'Washington DC',
    country: 'United States',
    region: 'North America',
    base_index: 88,
    housing_index: 90,
    food_index: 90,
    transport_index: 85,
    healthcare_index: 100,
    utilities_index: 88,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'austin',
    city_name: 'Austin',
    country: 'United States',
    region: 'North America',
    base_index: 75,
    housing_index: 70,
    food_index: 85,
    transport_index: 80,
    healthcare_index: 90,
    utilities_index: 90,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'miami',
    city_name: 'Miami',
    country: 'United States',
    region: 'North America',
    base_index: 78,
    housing_index: 80,
    food_index: 88,
    transport_index: 85,
    healthcare_index: 95,
    utilities_index: 88,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'denver',
    city_name: 'Denver',
    country: 'United States',
    region: 'North America',
    base_index: 73,
    housing_index: 72,
    food_index: 82,
    transport_index: 78,
    healthcare_index: 92,
    utilities_index: 75,
    tax_index: 88,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'chicago',
    city_name: 'Chicago',
    country: 'United States',
    region: 'North America',
    base_index: 77,
    housing_index: 75,
    food_index: 85,
    transport_index: 88,
    healthcare_index: 95,
    utilities_index: 92,
    tax_index: 92,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'atlanta',
    city_name: 'Atlanta',
    country: 'United States',
    region: 'North America',
    base_index: 68,
    housing_index: 65,
    food_index: 82,
    transport_index: 78,
    healthcare_index: 90,
    utilities_index: 85,
    tax_index: 90,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'dallas',
    city_name: 'Dallas',
    country: 'United States',
    region: 'North America',
    base_index: 65,
    housing_index: 60,
    food_index: 80,
    transport_index: 75,
    healthcare_index: 88,
    utilities_index: 88,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'houston',
    city_name: 'Houston',
    country: 'United States',
    region: 'North America',
    base_index: 62,
    housing_index: 58,
    food_index: 78,
    transport_index: 72,
    healthcare_index: 85,
    utilities_index: 90,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'phoenix',
    city_name: 'Phoenix',
    country: 'United States',
    region: 'North America',
    base_index: 65,
    housing_index: 62,
    food_index: 80,
    transport_index: 75,
    healthcare_index: 88,
    utilities_index: 95,
    tax_index: 87,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'portland',
    city_name: 'Portland',
    country: 'United States',
    region: 'North America',
    base_index: 78,
    housing_index: 82,
    food_index: 88,
    transport_index: 80,
    healthcare_index: 92,
    utilities_index: 78,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'nashville',
    city_name: 'Nashville',
    country: 'United States',
    region: 'North America',
    base_index: 68,
    housing_index: 68,
    food_index: 82,
    transport_index: 75,
    healthcare_index: 88,
    utilities_index: 85,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'raleigh',
    city_name: 'Raleigh',
    country: 'United States',
    region: 'North America',
    base_index: 65,
    housing_index: 62,
    food_index: 80,
    transport_index: 72,
    healthcare_index: 88,
    utilities_index: 82,
    tax_index: 90,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'san-diego',
    city_name: 'San Diego',
    country: 'United States',
    region: 'North America',
    base_index: 82,
    housing_index: 88,
    food_index: 88,
    transport_index: 82,
    healthcare_index: 95,
    utilities_index: 80,
    tax_index: 102,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'minneapolis',
    city_name: 'Minneapolis',
    country: 'United States',
    region: 'North America',
    base_index: 70,
    housing_index: 68,
    food_index: 82,
    transport_index: 78,
    healthcare_index: 92,
    utilities_index: 85,
    tax_index: 92,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'tampa',
    city_name: 'Tampa',
    country: 'United States',
    region: 'North America',
    base_index: 65,
    housing_index: 65,
    food_index: 82,
    transport_index: 75,
    healthcare_index: 88,
    utilities_index: 90,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'salt-lake',
    city_name: 'Salt Lake City',
    country: 'United States',
    region: 'North America',
    base_index: 68,
    housing_index: 70,
    food_index: 80,
    transport_index: 72,
    healthcare_index: 85,
    utilities_index: 78,
    tax_index: 88,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'las-vegas',
    city_name: 'Las Vegas',
    country: 'United States',
    region: 'North America',
    base_index: 62,
    housing_index: 60,
    food_index: 78,
    transport_index: 70,
    healthcare_index: 85,
    utilities_index: 88,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },

  // ============================================================================
  // CANADA
  // ============================================================================
  {
    city_id: 'toronto',
    city_name: 'Toronto',
    country: 'Canada',
    region: 'North America',
    base_index: 78,
    housing_index: 85,
    food_index: 82,
    transport_index: 80,
    healthcare_index: 55,
    utilities_index: 85,
    tax_index: 88,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'vancouver',
    city_name: 'Vancouver',
    country: 'Canada',
    region: 'North America',
    base_index: 82,
    housing_index: 95,
    food_index: 85,
    transport_index: 78,
    healthcare_index: 55,
    utilities_index: 80,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'montreal',
    city_name: 'Montreal',
    country: 'Canada',
    region: 'North America',
    base_index: 65,
    housing_index: 65,
    food_index: 78,
    transport_index: 72,
    healthcare_index: 55,
    utilities_index: 75,
    tax_index: 92,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'calgary',
    city_name: 'Calgary',
    country: 'Canada',
    region: 'North America',
    base_index: 68,
    housing_index: 70,
    food_index: 80,
    transport_index: 75,
    healthcare_index: 55,
    utilities_index: 82,
    tax_index: 82,
    data_year: 2025,
    confidence: 'high',
  },

  // ============================================================================
  // WESTERN EUROPE
  // ============================================================================
  {
    city_id: 'london',
    city_name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    base_index: 95,
    housing_index: 110,
    food_index: 90,
    transport_index: 105,
    healthcare_index: 60,
    utilities_index: 105,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'manchester',
    city_name: 'Manchester',
    country: 'United Kingdom',
    region: 'Europe',
    base_index: 68,
    housing_index: 65,
    food_index: 80,
    transport_index: 85,
    healthcare_index: 60,
    utilities_index: 95,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'paris',
    city_name: 'Paris',
    country: 'France',
    region: 'Europe',
    base_index: 92,
    housing_index: 105,
    food_index: 95,
    transport_index: 90,
    healthcare_index: 55,
    utilities_index: 98,
    tax_index: 105,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'lyon',
    city_name: 'Lyon',
    country: 'France',
    region: 'Europe',
    base_index: 72,
    housing_index: 70,
    food_index: 85,
    transport_index: 75,
    healthcare_index: 55,
    utilities_index: 90,
    tax_index: 105,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'berlin',
    city_name: 'Berlin',
    country: 'Germany',
    region: 'Europe',
    base_index: 72,
    housing_index: 75,
    food_index: 78,
    transport_index: 80,
    healthcare_index: 58,
    utilities_index: 95,
    tax_index: 98,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'munich',
    city_name: 'Munich',
    country: 'Germany',
    region: 'Europe',
    base_index: 85,
    housing_index: 95,
    food_index: 85,
    transport_index: 85,
    healthcare_index: 58,
    utilities_index: 95,
    tax_index: 98,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'amsterdam',
    city_name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    base_index: 88,
    housing_index: 100,
    food_index: 85,
    transport_index: 78,
    healthcare_index: 60,
    utilities_index: 98,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'dublin',
    city_name: 'Dublin',
    country: 'Ireland',
    region: 'Europe',
    base_index: 90,
    housing_index: 105,
    food_index: 88,
    transport_index: 85,
    healthcare_index: 62,
    utilities_index: 92,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'zurich',
    city_name: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    base_index: 125,
    housing_index: 140,
    food_index: 135,
    transport_index: 110,
    healthcare_index: 120,
    utilities_index: 100,
    tax_index: 75,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'geneva',
    city_name: 'Geneva',
    country: 'Switzerland',
    region: 'Europe',
    base_index: 130,
    housing_index: 145,
    food_index: 140,
    transport_index: 115,
    healthcare_index: 125,
    utilities_index: 105,
    tax_index: 72,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'vienna',
    city_name: 'Vienna',
    country: 'Austria',
    region: 'Europe',
    base_index: 75,
    housing_index: 78,
    food_index: 82,
    transport_index: 72,
    healthcare_index: 55,
    utilities_index: 88,
    tax_index: 92,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'copenhagen',
    city_name: 'Copenhagen',
    country: 'Denmark',
    region: 'Europe',
    base_index: 98,
    housing_index: 100,
    food_index: 105,
    transport_index: 90,
    healthcare_index: 58,
    utilities_index: 95,
    tax_index: 110,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'stockholm',
    city_name: 'Stockholm',
    country: 'Sweden',
    region: 'Europe',
    base_index: 92,
    housing_index: 95,
    food_index: 95,
    transport_index: 88,
    healthcare_index: 55,
    utilities_index: 85,
    tax_index: 108,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'oslo',
    city_name: 'Oslo',
    country: 'Norway',
    region: 'Europe',
    base_index: 110,
    housing_index: 110,
    food_index: 120,
    transport_index: 105,
    healthcare_index: 58,
    utilities_index: 92,
    tax_index: 105,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'helsinki',
    city_name: 'Helsinki',
    country: 'Finland',
    region: 'Europe',
    base_index: 88,
    housing_index: 88,
    food_index: 95,
    transport_index: 82,
    healthcare_index: 55,
    utilities_index: 88,
    tax_index: 100,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'brussels',
    city_name: 'Brussels',
    country: 'Belgium',
    region: 'Europe',
    base_index: 78,
    housing_index: 82,
    food_index: 85,
    transport_index: 78,
    healthcare_index: 55,
    utilities_index: 95,
    tax_index: 102,
    data_year: 2025,
    confidence: 'high',
  },

  // ============================================================================
  // SOUTHERN EUROPE
  // ============================================================================
  {
    city_id: 'barcelona',
    city_name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    base_index: 65,
    housing_index: 70,
    food_index: 68,
    transport_index: 60,
    healthcare_index: 50,
    utilities_index: 85,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'madrid',
    city_name: 'Madrid',
    country: 'Spain',
    region: 'Europe',
    base_index: 62,
    housing_index: 65,
    food_index: 65,
    transport_index: 58,
    healthcare_index: 50,
    utilities_index: 82,
    tax_index: 82,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'valencia',
    city_name: 'Valencia',
    country: 'Spain',
    region: 'Europe',
    base_index: 52,
    housing_index: 50,
    food_index: 58,
    transport_index: 52,
    healthcare_index: 48,
    utilities_index: 78,
    tax_index: 78,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'lisbon',
    city_name: 'Lisbon',
    country: 'Portugal',
    region: 'Europe',
    base_index: 58,
    housing_index: 62,
    food_index: 55,
    transport_index: 52,
    healthcare_index: 45,
    utilities_index: 78,
    tax_index: 75,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'porto',
    city_name: 'Porto',
    country: 'Portugal',
    region: 'Europe',
    base_index: 48,
    housing_index: 48,
    food_index: 50,
    transport_index: 45,
    healthcare_index: 42,
    utilities_index: 72,
    tax_index: 75,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'rome',
    city_name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    base_index: 70,
    housing_index: 75,
    food_index: 72,
    transport_index: 65,
    healthcare_index: 48,
    utilities_index: 90,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'milan',
    city_name: 'Milan',
    country: 'Italy',
    region: 'Europe',
    base_index: 78,
    housing_index: 88,
    food_index: 78,
    transport_index: 70,
    healthcare_index: 48,
    utilities_index: 92,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'florence',
    city_name: 'Florence',
    country: 'Italy',
    region: 'Europe',
    base_index: 68,
    housing_index: 72,
    food_index: 70,
    transport_index: 62,
    healthcare_index: 48,
    utilities_index: 88,
    tax_index: 95,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'athens',
    city_name: 'Athens',
    country: 'Greece',
    region: 'Europe',
    base_index: 52,
    housing_index: 50,
    food_index: 55,
    transport_index: 48,
    healthcare_index: 42,
    utilities_index: 75,
    tax_index: 78,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'split',
    city_name: 'Split',
    country: 'Croatia',
    region: 'Europe',
    base_index: 48,
    housing_index: 52,
    food_index: 50,
    transport_index: 42,
    healthcare_index: 38,
    utilities_index: 70,
    tax_index: 72,
    data_year: 2025,
    confidence: 'medium',
  },

  // ============================================================================
  // EASTERN EUROPE
  // ============================================================================
  {
    city_id: 'prague',
    city_name: 'Prague',
    country: 'Czech Republic',
    region: 'Europe',
    base_index: 52,
    housing_index: 55,
    food_index: 52,
    transport_index: 48,
    healthcare_index: 40,
    utilities_index: 72,
    tax_index: 70,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'budapest',
    city_name: 'Budapest',
    country: 'Hungary',
    region: 'Europe',
    base_index: 45,
    housing_index: 45,
    food_index: 45,
    transport_index: 40,
    healthcare_index: 35,
    utilities_index: 65,
    tax_index: 68,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'warsaw',
    city_name: 'Warsaw',
    country: 'Poland',
    region: 'Europe',
    base_index: 48,
    housing_index: 50,
    food_index: 48,
    transport_index: 42,
    healthcare_index: 38,
    utilities_index: 68,
    tax_index: 70,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'krakow',
    city_name: 'Krakow',
    country: 'Poland',
    region: 'Europe',
    base_index: 42,
    housing_index: 42,
    food_index: 42,
    transport_index: 38,
    healthcare_index: 35,
    utilities_index: 62,
    tax_index: 70,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'bucharest',
    city_name: 'Bucharest',
    country: 'Romania',
    region: 'Europe',
    base_index: 40,
    housing_index: 38,
    food_index: 40,
    transport_index: 35,
    healthcare_index: 32,
    utilities_index: 55,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'sofia',
    city_name: 'Sofia',
    country: 'Bulgaria',
    region: 'Europe',
    base_index: 38,
    housing_index: 35,
    food_index: 38,
    transport_index: 32,
    healthcare_index: 30,
    utilities_index: 52,
    tax_index: 60,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'tallinn',
    city_name: 'Tallinn',
    country: 'Estonia',
    region: 'Europe',
    base_index: 58,
    housing_index: 58,
    food_index: 60,
    transport_index: 52,
    healthcare_index: 42,
    utilities_index: 72,
    tax_index: 68,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'riga',
    city_name: 'Riga',
    country: 'Latvia',
    region: 'Europe',
    base_index: 50,
    housing_index: 48,
    food_index: 52,
    transport_index: 45,
    healthcare_index: 38,
    utilities_index: 65,
    tax_index: 72,
    data_year: 2025,
    confidence: 'medium',
  },

  // ============================================================================
  // ASIA - EAST ASIA
  // ============================================================================
  {
    city_id: 'tokyo',
    city_name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    base_index: 85,
    housing_index: 90,
    food_index: 80,
    transport_index: 75,
    healthcare_index: 70,
    utilities_index: 88,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'osaka',
    city_name: 'Osaka',
    country: 'Japan',
    region: 'Asia',
    base_index: 72,
    housing_index: 70,
    food_index: 72,
    transport_index: 68,
    healthcare_index: 68,
    utilities_index: 82,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'seoul',
    city_name: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    base_index: 78,
    housing_index: 88,
    food_index: 72,
    transport_index: 65,
    healthcare_index: 55,
    utilities_index: 78,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'busan',
    city_name: 'Busan',
    country: 'South Korea',
    region: 'Asia',
    base_index: 62,
    housing_index: 58,
    food_index: 65,
    transport_index: 55,
    healthcare_index: 52,
    utilities_index: 72,
    tax_index: 80,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'taipei',
    city_name: 'Taipei',
    country: 'Taiwan',
    region: 'Asia',
    base_index: 62,
    housing_index: 72,
    food_index: 55,
    transport_index: 48,
    healthcare_index: 45,
    utilities_index: 65,
    tax_index: 72,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'hong-kong',
    city_name: 'Hong Kong',
    country: 'Hong Kong',
    region: 'Asia',
    base_index: 95,
    housing_index: 135,
    food_index: 82,
    transport_index: 65,
    healthcare_index: 70,
    utilities_index: 88,
    tax_index: 65,
    data_year: 2025,
    confidence: 'high',
  },

  // ============================================================================
  // ASIA - SOUTHEAST ASIA
  // ============================================================================
  {
    city_id: 'singapore',
    city_name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    base_index: 92,
    housing_index: 125,
    food_index: 75,
    transport_index: 70,
    healthcare_index: 65,
    utilities_index: 80,
    tax_index: 70,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'bangkok',
    city_name: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    base_index: 48,
    housing_index: 45,
    food_index: 35,
    transport_index: 40,
    healthcare_index: 42,
    utilities_index: 52,
    tax_index: 60,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'chiang-mai',
    city_name: 'Chiang Mai',
    country: 'Thailand',
    region: 'Asia',
    base_index: 38,
    housing_index: 32,
    food_index: 30,
    transport_index: 28,
    healthcare_index: 35,
    utilities_index: 42,
    tax_index: 58,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'phuket',
    city_name: 'Phuket',
    country: 'Thailand',
    region: 'Asia',
    base_index: 45,
    housing_index: 42,
    food_index: 38,
    transport_index: 35,
    healthcare_index: 40,
    utilities_index: 48,
    tax_index: 58,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'kuala-lumpur',
    city_name: 'Kuala Lumpur',
    country: 'Malaysia',
    region: 'Asia',
    base_index: 45,
    housing_index: 42,
    food_index: 38,
    transport_index: 35,
    healthcare_index: 38,
    utilities_index: 48,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'penang',
    city_name: 'Penang',
    country: 'Malaysia',
    region: 'Asia',
    base_index: 40,
    housing_index: 38,
    food_index: 32,
    transport_index: 30,
    healthcare_index: 35,
    utilities_index: 42,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'ho-chi-minh',
    city_name: 'Ho Chi Minh City',
    country: 'Vietnam',
    region: 'Asia',
    base_index: 38,
    housing_index: 38,
    food_index: 28,
    transport_index: 25,
    healthcare_index: 35,
    utilities_index: 42,
    tax_index: 68,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'hanoi',
    city_name: 'Hanoi',
    country: 'Vietnam',
    region: 'Asia',
    base_index: 35,
    housing_index: 35,
    food_index: 25,
    transport_index: 22,
    healthcare_index: 32,
    utilities_index: 38,
    tax_index: 68,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'da-nang',
    city_name: 'Da Nang',
    country: 'Vietnam',
    region: 'Asia',
    base_index: 32,
    housing_index: 30,
    food_index: 22,
    transport_index: 20,
    healthcare_index: 30,
    utilities_index: 35,
    tax_index: 68,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'bali',
    city_name: 'Bali (Ubud)',
    country: 'Indonesia',
    region: 'Asia',
    base_index: 40,
    housing_index: 35,
    food_index: 32,
    transport_index: 30,
    healthcare_index: 35,
    utilities_index: 45,
    tax_index: 55,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'jakarta',
    city_name: 'Jakarta',
    country: 'Indonesia',
    region: 'Asia',
    base_index: 42,
    housing_index: 40,
    food_index: 32,
    transport_index: 28,
    healthcare_index: 38,
    utilities_index: 42,
    tax_index: 62,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'manila',
    city_name: 'Manila',
    country: 'Philippines',
    region: 'Asia',
    base_index: 42,
    housing_index: 45,
    food_index: 35,
    transport_index: 28,
    healthcare_index: 38,
    utilities_index: 48,
    tax_index: 70,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'cebu',
    city_name: 'Cebu',
    country: 'Philippines',
    region: 'Asia',
    base_index: 35,
    housing_index: 32,
    food_index: 30,
    transport_index: 25,
    healthcare_index: 32,
    utilities_index: 42,
    tax_index: 70,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'phnom-penh',
    city_name: 'Phnom Penh',
    country: 'Cambodia',
    region: 'Asia',
    base_index: 38,
    housing_index: 35,
    food_index: 28,
    transport_index: 22,
    healthcare_index: 32,
    utilities_index: 42,
    tax_index: 55,
    data_year: 2025,
    confidence: 'low',
  },

  // ============================================================================
  // ASIA - SOUTH ASIA
  // ============================================================================
  {
    city_id: 'mumbai',
    city_name: 'Mumbai',
    country: 'India',
    region: 'Asia',
    base_index: 38,
    housing_index: 55,
    food_index: 25,
    transport_index: 22,
    healthcare_index: 30,
    utilities_index: 35,
    tax_index: 75,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'bangalore',
    city_name: 'Bangalore',
    country: 'India',
    region: 'Asia',
    base_index: 35,
    housing_index: 42,
    food_index: 22,
    transport_index: 20,
    healthcare_index: 28,
    utilities_index: 32,
    tax_index: 75,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'goa',
    city_name: 'Goa',
    country: 'India',
    region: 'Asia',
    base_index: 32,
    housing_index: 35,
    food_index: 20,
    transport_index: 18,
    healthcare_index: 25,
    utilities_index: 30,
    tax_index: 75,
    data_year: 2025,
    confidence: 'medium',
  },

  // ============================================================================
  // MIDDLE EAST
  // ============================================================================
  {
    city_id: 'dubai',
    city_name: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    base_index: 70,
    housing_index: 80,
    food_index: 75,
    transport_index: 65,
    healthcare_index: 85,
    utilities_index: 55,
    tax_index: 0,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'abu-dhabi',
    city_name: 'Abu Dhabi',
    country: 'United Arab Emirates',
    region: 'Middle East',
    base_index: 68,
    housing_index: 75,
    food_index: 72,
    transport_index: 62,
    healthcare_index: 82,
    utilities_index: 52,
    tax_index: 0,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'tel-aviv',
    city_name: 'Tel Aviv',
    country: 'Israel',
    region: 'Middle East',
    base_index: 95,
    housing_index: 115,
    food_index: 95,
    transport_index: 82,
    healthcare_index: 75,
    utilities_index: 88,
    tax_index: 92,
    data_year: 2025,
    confidence: 'high',
  },

  // ============================================================================
  // OCEANIA
  // ============================================================================
  {
    city_id: 'sydney',
    city_name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    base_index: 88,
    housing_index: 100,
    food_index: 90,
    transport_index: 85,
    healthcare_index: 65,
    utilities_index: 88,
    tax_index: 88,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'melbourne',
    city_name: 'Melbourne',
    country: 'Australia',
    region: 'Oceania',
    base_index: 82,
    housing_index: 88,
    food_index: 85,
    transport_index: 82,
    healthcare_index: 65,
    utilities_index: 85,
    tax_index: 88,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'brisbane',
    city_name: 'Brisbane',
    country: 'Australia',
    region: 'Oceania',
    base_index: 72,
    housing_index: 72,
    food_index: 80,
    transport_index: 75,
    healthcare_index: 65,
    utilities_index: 82,
    tax_index: 88,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'auckland',
    city_name: 'Auckland',
    country: 'New Zealand',
    region: 'Oceania',
    base_index: 78,
    housing_index: 85,
    food_index: 82,
    transport_index: 75,
    healthcare_index: 60,
    utilities_index: 80,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'wellington',
    city_name: 'Wellington',
    country: 'New Zealand',
    region: 'Oceania',
    base_index: 72,
    housing_index: 75,
    food_index: 78,
    transport_index: 70,
    healthcare_index: 60,
    utilities_index: 78,
    tax_index: 85,
    data_year: 2025,
    confidence: 'high',
  },

  // ============================================================================
  // LATIN AMERICA - MEXICO
  // ============================================================================
  {
    city_id: 'mexico-city',
    city_name: 'Mexico City',
    country: 'Mexico',
    region: 'Latin America',
    base_index: 45,
    housing_index: 40,
    food_index: 42,
    transport_index: 35,
    healthcare_index: 38,
    utilities_index: 50,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'playa-del-carmen',
    city_name: 'Playa del Carmen',
    country: 'Mexico',
    region: 'Latin America',
    base_index: 48,
    housing_index: 50,
    food_index: 45,
    transport_index: 35,
    healthcare_index: 40,
    utilities_index: 52,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'guadalajara',
    city_name: 'Guadalajara',
    country: 'Mexico',
    region: 'Latin America',
    base_index: 40,
    housing_index: 35,
    food_index: 38,
    transport_index: 32,
    healthcare_index: 35,
    utilities_index: 45,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'oaxaca',
    city_name: 'Oaxaca',
    country: 'Mexico',
    region: 'Latin America',
    base_index: 35,
    housing_index: 30,
    food_index: 32,
    transport_index: 28,
    healthcare_index: 32,
    utilities_index: 40,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'merida',
    city_name: 'Merida',
    country: 'Mexico',
    region: 'Latin America',
    base_index: 38,
    housing_index: 35,
    food_index: 35,
    transport_index: 30,
    healthcare_index: 35,
    utilities_index: 48,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'san-miguel',
    city_name: 'San Miguel de Allende',
    country: 'Mexico',
    region: 'Latin America',
    base_index: 42,
    housing_index: 45,
    food_index: 40,
    transport_index: 32,
    healthcare_index: 38,
    utilities_index: 48,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },

  // ============================================================================
  // LATIN AMERICA - CENTRAL AMERICA
  // ============================================================================
  {
    city_id: 'panama-city',
    city_name: 'Panama City',
    country: 'Panama',
    region: 'Latin America',
    base_index: 52,
    housing_index: 55,
    food_index: 50,
    transport_index: 42,
    healthcare_index: 48,
    utilities_index: 55,
    tax_index: 55,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'san-jose-cr',
    city_name: 'San Jose',
    country: 'Costa Rica',
    region: 'Latin America',
    base_index: 55,
    housing_index: 52,
    food_index: 55,
    transport_index: 45,
    healthcare_index: 50,
    utilities_index: 58,
    tax_index: 62,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'antigua',
    city_name: 'Antigua',
    country: 'Guatemala',
    region: 'Latin America',
    base_index: 38,
    housing_index: 35,
    food_index: 32,
    transport_index: 25,
    healthcare_index: 32,
    utilities_index: 42,
    tax_index: 58,
    data_year: 2025,
    confidence: 'low',
  },

  // ============================================================================
  // LATIN AMERICA - SOUTH AMERICA
  // ============================================================================
  {
    city_id: 'buenos-aires',
    city_name: 'Buenos Aires',
    country: 'Argentina',
    region: 'Latin America',
    base_index: 42,
    housing_index: 38,
    food_index: 40,
    transport_index: 35,
    healthcare_index: 45,
    utilities_index: 48,
    tax_index: 70,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'mendoza',
    city_name: 'Mendoza',
    country: 'Argentina',
    region: 'Latin America',
    base_index: 35,
    housing_index: 32,
    food_index: 35,
    transport_index: 28,
    healthcare_index: 40,
    utilities_index: 42,
    tax_index: 70,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'medellin',
    city_name: 'Medellin',
    country: 'Colombia',
    region: 'Latin America',
    base_index: 43,
    housing_index: 40,
    food_index: 38,
    transport_index: 32,
    healthcare_index: 40,
    utilities_index: 48,
    tax_index: 62,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'bogota',
    city_name: 'Bogota',
    country: 'Colombia',
    region: 'Latin America',
    base_index: 45,
    housing_index: 42,
    food_index: 40,
    transport_index: 35,
    healthcare_index: 42,
    utilities_index: 50,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'cartagena',
    city_name: 'Cartagena',
    country: 'Colombia',
    region: 'Latin America',
    base_index: 48,
    housing_index: 48,
    food_index: 42,
    transport_index: 35,
    healthcare_index: 42,
    utilities_index: 52,
    tax_index: 62,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'lima',
    city_name: 'Lima',
    country: 'Peru',
    region: 'Latin America',
    base_index: 45,
    housing_index: 42,
    food_index: 42,
    transport_index: 35,
    healthcare_index: 40,
    utilities_index: 48,
    tax_index: 68,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'cusco',
    city_name: 'Cusco',
    country: 'Peru',
    region: 'Latin America',
    base_index: 38,
    housing_index: 35,
    food_index: 35,
    transport_index: 28,
    healthcare_index: 35,
    utilities_index: 42,
    tax_index: 68,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'santiago',
    city_name: 'Santiago',
    country: 'Chile',
    region: 'Latin America',
    base_index: 52,
    housing_index: 52,
    food_index: 52,
    transport_index: 45,
    healthcare_index: 48,
    utilities_index: 55,
    tax_index: 72,
    data_year: 2025,
    confidence: 'high',
  },
  {
    city_id: 'sao-paulo',
    city_name: 'Sao Paulo',
    country: 'Brazil',
    region: 'Latin America',
    base_index: 50,
    housing_index: 52,
    food_index: 48,
    transport_index: 42,
    healthcare_index: 48,
    utilities_index: 52,
    tax_index: 75,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'rio',
    city_name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'Latin America',
    base_index: 48,
    housing_index: 55,
    food_index: 45,
    transport_index: 40,
    healthcare_index: 45,
    utilities_index: 50,
    tax_index: 75,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'florianopolis',
    city_name: 'Florianopolis',
    country: 'Brazil',
    region: 'Latin America',
    base_index: 42,
    housing_index: 45,
    food_index: 40,
    transport_index: 35,
    healthcare_index: 42,
    utilities_index: 45,
    tax_index: 75,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'montevideo',
    city_name: 'Montevideo',
    country: 'Uruguay',
    region: 'Latin America',
    base_index: 55,
    housing_index: 55,
    food_index: 55,
    transport_index: 48,
    healthcare_index: 52,
    utilities_index: 58,
    tax_index: 72,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'quito',
    city_name: 'Quito',
    country: 'Ecuador',
    region: 'Latin America',
    base_index: 42,
    housing_index: 40,
    food_index: 38,
    transport_index: 32,
    healthcare_index: 38,
    utilities_index: 45,
    tax_index: 60,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'cuenca',
    city_name: 'Cuenca',
    country: 'Ecuador',
    region: 'Latin America',
    base_index: 35,
    housing_index: 32,
    food_index: 32,
    transport_index: 25,
    healthcare_index: 32,
    utilities_index: 38,
    tax_index: 60,
    data_year: 2025,
    confidence: 'medium',
  },

  // ============================================================================
  // CARIBBEAN
  // ============================================================================
  {
    city_id: 'san-juan',
    city_name: 'San Juan',
    country: 'Puerto Rico',
    region: 'Caribbean',
    base_index: 68,
    housing_index: 65,
    food_index: 75,
    transport_index: 70,
    healthcare_index: 80,
    utilities_index: 85,
    tax_index: 70,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'santo-domingo',
    city_name: 'Santo Domingo',
    country: 'Dominican Republic',
    region: 'Caribbean',
    base_index: 42,
    housing_index: 40,
    food_index: 42,
    transport_index: 35,
    healthcare_index: 38,
    utilities_index: 55,
    tax_index: 62,
    data_year: 2025,
    confidence: 'low',
  },

  // ============================================================================
  // AFRICA
  // ============================================================================
  {
    city_id: 'cape-town',
    city_name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    base_index: 42,
    housing_index: 45,
    food_index: 40,
    transport_index: 35,
    healthcare_index: 48,
    utilities_index: 52,
    tax_index: 78,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'johannesburg',
    city_name: 'Johannesburg',
    country: 'South Africa',
    region: 'Africa',
    base_index: 40,
    housing_index: 42,
    food_index: 38,
    transport_index: 32,
    healthcare_index: 45,
    utilities_index: 50,
    tax_index: 78,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'nairobi',
    city_name: 'Nairobi',
    country: 'Kenya',
    region: 'Africa',
    base_index: 38,
    housing_index: 40,
    food_index: 35,
    transport_index: 28,
    healthcare_index: 42,
    utilities_index: 48,
    tax_index: 72,
    data_year: 2025,
    confidence: 'low',
  },
  {
    city_id: 'cairo',
    city_name: 'Cairo',
    country: 'Egypt',
    region: 'Africa',
    base_index: 32,
    housing_index: 30,
    food_index: 28,
    transport_index: 22,
    healthcare_index: 32,
    utilities_index: 35,
    tax_index: 62,
    data_year: 2025,
    confidence: 'medium',
  },
  {
    city_id: 'marrakech',
    city_name: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    base_index: 38,
    housing_index: 35,
    food_index: 32,
    transport_index: 25,
    healthcare_index: 35,
    utilities_index: 42,
    tax_index: 65,
    data_year: 2025,
    confidence: 'medium',
  },
];

/**
 * Default spending category weights
 * These represent typical spending distribution in retirement
 * Users can adjust these based on their lifestyle
 */
export const DEFAULT_WEIGHTS = {
  housing: 0.35,    // Rent/mortgage, property taxes
  food: 0.15,       // Groceries and dining out
  transport: 0.10,  // Car, gas, public transport
  healthcare: 0.10, // Insurance, medical expenses
  utilities: 0.10,  // Electricity, water, internet, phone
  lifestyle: 0.20,  // Entertainment, travel, hobbies (uses base_index)
};

/**
 * Get city by ID
 */
export function getCityById(cityId: string): CityData | undefined {
  return CITIES.find(c => c.city_id === cityId);
}

/**
 * Get cities sorted by base cost of living
 */
export function getCitiesSortedByCost(ascending = true): CityData[] {
  return [...CITIES].sort((a, b) =>
    ascending ? a.base_index - b.base_index : b.base_index - a.base_index
  );
}

/**
 * Get cities by country
 */
export function getCitiesByCountry(country: string): CityData[] {
  return CITIES.filter(c => c.country === country);
}

/**
 * Get cities by region
 */
export function getCitiesByRegion(region: string): CityData[] {
  return CITIES.filter(c => c.region === region);
}

/**
 * Get unique regions
 */
export function getRegions(): string[] {
  return [...new Set(CITIES.map(c => c.region))].sort();
}

/**
 * Get unique countries
 */
export function getCountries(): string[] {
  return [...new Set(CITIES.map(c => c.country))].sort();
}
