// Credit Card Family options (sorted alphabetically)
export const CREDIT_CARD_FAMILIES = [
  'Ally Bank',
  'American Express (Amex)',
  'Bank of America',
  'Barclays',
  'BMO Harris',
  'Bread Financial',
  'Capital One',
  'Chase',
  'Citi',
  'Citizens Bank',
  'Comenity',
  'Comerica',
  'Discover',
  'Fifth Third Bank',
  'First Citizens Bank',
  'HSBC',
  'Huntington Bank',
  'KeyBank',
  'Navy Federal Credit Union',
  'PNC',
  'Regions Bank',
  'Santander',
  'SoFi',
  'Synchrony',
  'TD Bank',
  'Truist',
  'U.S. Bank',
  'Upgrade',
  'Wells Fargo',
] as const;

// Rewards Category options (sorted alphabetically)
export const REWARDS_CATEGORIES = [
  'airline miles',
  'cash back',
  'dining rewards',
  'entertainment',
  'gas & EV charging',
  'grocery rewards',
  'hotel points',
  'rotating categories',
  'streaming services',
  'travel rewards',
] as const;
